### ISSUE TITLE
Availability of 25GBCT2 stepper motor

### ISSUE THREAD

**Issue by twitchyliquid64** [stanleyondrus/LaserProjectorV2#1]
I was wondering if you had any remaining sources you knew of for the stepper you used? I couldn't find it on aliexpress, I even went to the same seller as the page in your video.

Have you tried the more common 28BYJ-48 motors? My guess is the reduction in those is a little too high / motor is too slow to draw lines?

**Comment by stanleyondrus** [comment]
Unfortunately, I'm not able to find 25GBCT2 for purchase anywhere anymore.
28BYJ-48 are 1:64 so exactly as you said, it would be too slow.

**Comment by twitchyliquid64** [comment]
Thats a shame :/ I'll try and find a replacement. You mentioned briefly in the video that NEMA stepper motors weren't ideal: was that because of the weight being too much to move quickly or not having enough stepping granularity?

Also, were you microstepping the 25GBCT2's? Your code has `#define MICROSTEPS 1` but then seems to pull both mode pins low, which i thought was a full-step mode?

**Comment by stanleyondrus** [comment]
Not really sure what the problem was but I wasn't able to get sufficient torque at high speed.
Defining MICROSTEPS 1 basically means full-step mode. To use microstepping, set it to 4,8,16,..., and pull the mode pins to corresponding values.

**Comment by twitchyliquid64** [comment]
The A or B configurations of these boiz might be ideal?

https://www.aliexpress.us/item/3256803023172572.html

Considering buying a bunch and giving them a go.

**Comment by a2luca** [comment]
First of all awesome project, very nice!
Would be very nice to find a good replacement motor. I am also interested in building this laser projector myself.

**Comment by twitchyliquid64** [comment]
Apparently the B configuration (1:42 ratio) yields a step angle of 0.43 degrees, so that might work?

(I messaged the seller)

**Comment by stanleyondrus** [comment]
I would probably go for geared assemblies based on 15mm GM12-15BY (like the one @twitchyliquid64) or smaller 10mm GM12-10BY stepper motors. They have a step angle of 18° (20 steps per revolution), so even with 1:21 gearing ratio, you would get 18°/21=0.857° step angle.
